### ISSUE TITLE
是否考虑在扩展界面增加一个按钮链接到铭记之旅页面

### ISSUE THREAD

**Issue by Patrick-Ze** [KeyPJ/seelie-crx#1]
感谢大佬开发的扩展，我之前一直用的油猴插件版，扩展版稳定了很多👍
如题，是否考虑在扩展界面增加一个按钮链接到铭记之旅页面呢？根据选择的是国服/国际服跳转到对应的铭记之旅页面。目前登录过期时，要去之前的油猴脚本里寻找登录链接。

**Comment by KeyPJ** [comment]
我记得，当初开发时对失败请求就是，浏览器弹出提醒并打开新窗口啊
[对获取账户的请求](https://github.com/KeyPJ/seelie-crx/blob/4ba830a26d29d09c171cdbd351e4b4e4a70a027c/src/pages/background/hoyo.ts#L48)
[对账户内角色的请求](https://github.com/KeyPJ/seelie-crx/blob/4ba830a26d29d09c171cdbd351e4b4e4a70a027c/src/pages/background/hoyo.ts#L78)
```
       chrome.notifications.create(
            {iconUrl: "/icon-34.png", message, title: "", type: "basic"}
        )
        await chrome.tabs.create({url: isGlobal(region) ? BBS_URL_GLOBAL : BBS_URL})
        return [];
```

**Comment by Patrick-Ze** [comment]
感谢大佬解答，是我使用有问题。我没找到链接到仙灵之旅的按钮，所以是自己先去仙灵之旅网页看是否登录，再回来同步信息。
没想到已经做了处理👍
